#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : R-listenv
Version  : 0.7.0
Release  : 6
URL      : https://cran.r-project.org/src/contrib/listenv_0.7.0.tar.gz
Source0  : https://cran.r-project.org/src/contrib/listenv_0.7.0.tar.gz
Summary  : Environments Behaving (Almost) as Lists
Group    : Development/Tools
License  : LGPL-2.1
BuildRequires : clr-R-helpers

%description
No detailed description available

%prep
%setup -q -c -n listenv

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1526836907

%install
rm -rf %{buildroot}
export SOURCE_DATE_EPOCH=1526836907
export LANG=C
export CFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FCFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export CXXFLAGS="$CXXFLAGS -O3 -flto -fno-semantic-interposition "
export AR=gcc-ar
export RANLIB=gcc-ranlib
export LDFLAGS="$LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library

mkdir -p ~/.R
mkdir -p ~/.stash
echo "CFLAGS = $CFLAGS -march=haswell -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=haswell -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=haswell -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library listenv
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx2 ; mv $i.avx2 ~/.stash/; done
echo "CFLAGS = $CFLAGS -march=skylake-avx512 -ftree-vectorize -mprefer-vector-width=512 " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=skylake-avx512 -ftree-vectorize -mprefer-vector-width=512 " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=skylake-avx512 -ftree-vectorize -mprefer-vector-width=512  " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --no-test-load --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library listenv
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx512 ; mv $i.avx512 ~/.stash/; done
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library listenv
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc -l %{buildroot}/usr/lib64/R/library listenv|| : 
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :


%files
%defattr(-,root,root,-)
/usr/lib64/R/library/listenv/DESCRIPTION
/usr/lib64/R/library/listenv/INDEX
/usr/lib64/R/library/listenv/Meta/Rd.rds
/usr/lib64/R/library/listenv/Meta/features.rds
/usr/lib64/R/library/listenv/Meta/hsearch.rds
/usr/lib64/R/library/listenv/Meta/links.rds
/usr/lib64/R/library/listenv/Meta/nsInfo.rds
/usr/lib64/R/library/listenv/Meta/package.rds
/usr/lib64/R/library/listenv/Meta/vignette.rds
/usr/lib64/R/library/listenv/NAMESPACE
/usr/lib64/R/library/listenv/NEWS
/usr/lib64/R/library/listenv/R/listenv
/usr/lib64/R/library/listenv/R/listenv.rdb
/usr/lib64/R/library/listenv/R/listenv.rdx
/usr/lib64/R/library/listenv/doc/index.html
/usr/lib64/R/library/listenv/doc/listenv.html
/usr/lib64/R/library/listenv/doc/listenv.md.rsp
/usr/lib64/R/library/listenv/help/AnIndex
/usr/lib64/R/library/listenv/help/aliases.rds
/usr/lib64/R/library/listenv/help/listenv.rdb
/usr/lib64/R/library/listenv/help/listenv.rdx
/usr/lib64/R/library/listenv/help/paths.rds
/usr/lib64/R/library/listenv/html/00Index.html
/usr/lib64/R/library/listenv/html/R.css
/usr/lib64/R/library/listenv/tests/as.listenv.R
/usr/lib64/R/library/listenv/tests/as.vector.R
/usr/lib64/R/library/listenv/tests/get_variable,dimensions.R
/usr/lib64/R/library/listenv/tests/get_variable.R
/usr/lib64/R/library/listenv/tests/listenv,dimensions.R
/usr/lib64/R/library/listenv/tests/listenv.R
/usr/lib64/R/library/listenv/tests/parse_env_subset,dimensions.R
/usr/lib64/R/library/listenv/tests/parse_env_subset.R
/usr/lib64/R/library/listenv/tests/undim.R
/usr/lib64/R/library/listenv/tests/utils.R
